Fixing population MCMC
pints-team/pints pull request #1246
Opened 2021-01-11 17:14 UTC by MichaelClerx

@ben18785 could you have a look at this too?

- pop mcmc gave very odd distributions, and accepted very unlikely points (#1238)
- discovered two bugs, both in way exchange was handled
- fixed now, but performance still awful, because the base chain can suddenly jump to very unlikely points from the other chains. This _always_ gives a distribution that is far too wide, and the effect gets stronger with more iterations

Am I missing something?

2021-01-13 17:01 UTC, ben18785 requested changes
@MichaelClerx thanks for this. I've noticed something that I think looks a bit fishy.

Re: why it's not working: I just coded up population MCMC in R and checked it on your example. It works fine (pdf results attached)
[s_population_mcmc.pdf](https://github.com/pints-team/pints/files/5810045/s_population_mcmc.pdf)

, so there's definitely a bug.

2021-01-14 10:00 UTC, MichaelClerx commented on pints/_mcmc/_population.py
> +        #   log(A) = f_i(x_j) + f_j(x_i) - f_i(x_i) - f_j(x_j)
I was using `f_i` to denote the tempered log likelihood, `p_i` for the tempered likelihood.
We could calculate the p's, if you prefer?

2021-01-14 10:01 UTC, MichaelClerx commented on pints/_mcmc/_population.py
> +        tji = (1 - self._schedule[self._j]) * fi
Yeah just trying to rewrite for maximal clarity!

2021-01-14 10:23 UTC, MichaelClerx commented on pints/_mcmc/_population.py
> +            if b >= 0 or b >= np.log(np.random.uniform(0, 1)):
It's a cheeky optimisation: if (b >= 0) the RHS of the `or` is never evaluated, saving us a random sampling operation

2021-01-14 12:04 UTC, MichaelClerx commented on pints/_mcmc/_population.py
> +                self._chains[self._j].replace(xi, tji)
Our array holds untempered, but the chains hold the tempered ones, no? so that they (unwittingly) operate on the tempered space?

2021-01-14 13:06 UTC, ben18785 commented on pints/_mcmc/_population.py
> +        #   log(A) = f_i(x_j) + f_j(x_i) - f_i(x_i) - f_j(x_j)
No that's fine, I think

2021-01-14 13:06 UTC, ben18785 commented on pints/_mcmc/_population.py
> +            if b >= 0 or b >= np.log(np.random.uniform(0, 1)):
Cool, makes sense.

2021-01-14 13:14 UTC, ben18785 commented on pints/_mcmc/_population.py
> +                self._chains[self._j].replace(xi, tji)
Yes, you're right. Sorry.

2021-01-14 13:19 UTC, ben18785 requested changes
Thanks for answering my comments. Things that I think are worth trying:

- turn off / comment out the exchange step and see if things then work fine. If they don't then it's some issue with the way in which we're doing the chain-wise ACMC or could be that we're returning the wrong chain at the end
- turn off the ACMC step. I.e. just do the exchange. This should still yield a distribution that converges to the correct one

2021-01-14 13:34 UTC, MichaelClerx commented
Will try!

At the moment we just re-use the global values for x0 and sigma in all the subsamplers, when initialising:

        self._chains = [self._method(self._x0, self._sigma0) for i in range(n)]

is that OK?

2021-01-14 13:36 UTC, ben18785 commented
yeah, that should be fine

On Thu, Jan 14, 2021 at 1:34 PM Michael Clerx <notifications@github.com>
wrote:

> Will try!
>
> At the moment we just re-use the global values for x0 and sigma in all the
> subsamplers, when initialising:
>
>     self._chains = [self._method(self._x0, self._sigma0) for i in range(n)]
>
> is that OK?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pints-team/pints/pull/1246#issuecomment-760199635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCILKARQOS76YS3XXFKWDLSZ3XGHANCNFSM4V533FTA>
> .
>

2021-01-14 16:55 UTC, MichaelClerx commented
> turn off the ACMC step. I.e. just do the exchange. This should still yield a distribution that converges to the correct one

This would be a random sample of the 10 initial points then, but in the correct distribution?

2021-01-14 17:46 UTC, ben18785 commented
Erm, yes, you're right. Ha: without perturbation we can't do that. So maybe
just do ACMC thing where you turn off the exchanging?

On Thu, Jan 14, 2021 at 4:56 PM Michael Clerx <notifications@github.com>
wrote:

> turn off the ACMC step. I.e. just do the exchange. This should still yield
> a distribution that converges to the correct one
>
> This would be a random sample of the 10 initial points then, but in the
> correct distribution?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pints-team/pints/pull/1246#issuecomment-760324853>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABCILKA4GS5FBGG52J6KJQDSZ4O23ANCNFSM4V533FTA>
> .
>

2021-01-14 18:07 UTC, MichaelClerx commented
Aaaaaaargh it was a memory issue!
when the points were switched around it just switched refs so then changing one point changed the other one too. Think I've fixed it now

2021-01-14 20:52 UTC, MichaelClerx commented
Uploaded new fixes and removed old debug code. Note this passes all tests, but "better cod hub" has suddenly appeared alongside them

2021-01-19 13:03 UTC, ben18785 approved these changes
Thanks @MichaelClerx I'm happy with this to go in. Your changes to the bit re: memory allocation looks good to me.

2021-01-19 13:03 UTC, merged