Renamed function to change point tests.
pints-team/pints pull request #1392
Opened 2021-08-17 11:58 UTC by MichaelClerx

See #1391.

How's this?

2021-08-17 12:00 UTC, MichaelClerx commented
I'm just doing a quick re-run of the method merge tests, so a quick yes or no on this one would be very helpful 😅😅😅

2021-08-24 11:30 UTC, fcooper8472 requested changes
Looks good, except we now have a whole bunch of

```
import pints.cptests as ft
```

Change to `cp` or `cpt`?

2021-08-24 11:35 UTC, MichaelClerx commented
@fcooper8472 Done!

2021-08-24 12:07 UTC, fcooper8472 approved these changes

2021-08-24 13:30 UTC, merged